const videoData = [
  {
    idx: 1,
    title: "",
    thumbnail: "thumbnail_00",
    type: "COMMERCIAL",
    url: "https://youtu.be/tJhXIHkwhLI",
  },
  {
    idx: 2,
    title: "",
    thumbnail: "thumbnail_01",
    type: "COMMERCIAL",
    url: "https://youtu.be/HzHB6_UyPKE",
  },
  {
    idx: 3,
    title: "",
    thumbnail: "thumbnail_02",
    type: "COMMERCIAL",
    url: "https://youtu.be/lHTeYrcj9ag",
  },
  {
    idx: 4,
    title: "",
    thumbnail: "thumbnail_03",
    type: "COMMERCIAL",
    url: "https://youtu.be/xEU36UI5tEM",
  },
  {
    idx: 5,
    title: "",
    thumbnail: "thumbnail_04",
    type: "COMMERCIAL",
    url: "https://youtu.be/s38u82Fl70A",
  },
  {
    idx: 6,
    title: "",
    thumbnail: "thumbnail_05",
    type: "COMMERCIAL",
    url: "https://youtu.be/hnip2GFTS9Q",
  },
  {
    idx: 7,
    title: "",
    thumbnail: "thumbnail_06",
    type: "COMMERCIAL",
    url: "https://youtu.be/Dx_BPa_vYbM",
  },
  {
    idx: 8,
    title: "",
    thumbnail: "thumbnail_07",
    type: "COMMERCIAL",
    url: "https://youtu.be/zyik8yYzBqQ",
  },
  {
    idx: 9,
    title: "",
    thumbnail: "thumbnail_08",
    type: "CONTENTS",
    url: "https://youtu.be/TRBkxa53Ljw",
  },
  {
    idx: 10,
    title: "",
    thumbnail: "thumbnail_09",
    type: "COMMERCIAL",
    url: "https://youtu.be/mMONFZNBOqw",
  },
  {
    idx: 11,
    title: "",
    thumbnail: "thumbnail_10",
    type: "SHORTS",
    url: "https://youtu.be/qSxXcAHxP3E",
  },
  {
    idx: 12,
    title: "",
    thumbnail: "thumbnail_11",
    type: "COMMERCIAL",
    url: "https://youtu.be/U16_RjF8aRw",
  },
  {
    idx: 13,
    title: "",
    thumbnail: "thumbnail_12",
    type: "COMMERCIAL",
    url: "https://youtu.be/SBzFjIuVnxg",
  },
  {
    idx: 14,
    title: "",
    thumbnail: "thumbnail_13",
    type: "COMMERCIAL",
    url: "https://youtu.be/iDUOryghiOI",
  },
  {
    idx: 15,
    title: "",
    thumbnail: "thumbnail_14",
    type: "COMMERCIAL",
    url: "https://youtu.be/pnjKCOFbltg",
  },
  {
    idx: 16,
    title: "",
    thumbnail: "thumbnail_15",
    type: "M/V",
    url: "https://youtu.be/0i6m1Ergj5A",
  },
  {
    idx: 17,
    title: "",
    thumbnail: "thumbnail_16",
    type: "COMMERCIAL",
    url: "https://youtu.be/RJxu_jJxzdU",
  },
  {
    idx: 18,
    title: "",
    thumbnail: "thumbnail_17",
    type: "COMMERCIAL",
    url: "https://youtu.be/hC-R6uyHmvw",
  },
  {
    idx: 19,
    title: "",
    thumbnail: "thumbnail_18",
    type: "COMMERCIAL",
    url: "https://youtu.be/NGJS3e0bMCQ",
  },
  {
    idx: 20,
    title: "",
    thumbnail: "thumbnail_19",
    type: "CONTENTS",
    url: "https://youtu.be/9aA9A7mxILc",
  },
  {
    idx: 21,
    title: "",
    thumbnail: "thumbnail_20",
    type: "CONTENTS",
    url: "https://youtu.be/Zi6wEeaAQJo",
  },
  {
    idx: 22,
    title: "",
    thumbnail: "thumbnail_21",
    type: "CONTENTS",
    url: "https://youtu.be/0Ixuw20g-1U",
  },
  {
    idx: 23,
    title: "",
    thumbnail: "thumbnail_22",
    type: "CONTENTS",
    url: "https://youtu.be/-DDx_Ae2IpU",
  },
  {
    idx: 24,
    title: "",
    thumbnail: "thumbnail_23",
    type: "CONTENTS",
    url: "https://youtu.be/0EJkMqpDBfg",
  },
  {
    idx: 25,
    title: "",
    thumbnail: "thumbnail_24",
    type: "CONTENTS",
    url: "https://youtu.be/8AuMK68SNbs",
  },
  {
    idx: 26,
    title: "",
    thumbnail: "thumbnail_25",
    type: "CONTENTS",
    url: "https://youtu.be/KxSTnhF5yAg",
  },
  {
    idx: 27,
    title: "",
    thumbnail: "thumbnail_26",
    type: "CONTENTS",
    url: "https://youtu.be/JduysLOH8MA",
  },
  {
    idx: 28,
    title: "",
    thumbnail: "thumbnail_27",
    type: "CONTENTS",
    url: "https://youtu.be/2wWOUZ4S_RE",
  },
  {
    idx: 29,
    title: "",
    thumbnail: "thumbnail_28",
    type: "CONTENTS",
    url: "https://youtu.be/M2Iia12epxo",
  },
  {
    idx: 30,
    title: "",
    thumbnail: "thumbnail_29",
    type: "CONTENTS",
    url: "https://youtu.be/jMI2-BlmFKA",
  },
  {
    idx: 31,
    title: "",
    thumbnail: "thumbnail_30",
    type: "CONTENTS",
    url: "https://youtu.be/h4sJXplT9Dk",
  },
  {
    idx: 32,
    title: "",
    thumbnail: "thumbnail_31",
    type: "CONTENTS",
    url: "https://youtu.be/UuR2MIdlBFM",
  },
  {
    idx: 33,
    title: "",
    thumbnail: "thumbnail_32",
    type: "CONTENTS",
    url: "https://youtu.be/TEQAt95c6Fc",
  },
  {
    idx: 34,
    title: "",
    thumbnail: "thumbnail_33",
    type: "CONTENTS",
    url: "https://youtu.be/sa-_L-kAt7g",
  },
  {
    idx: 35,
    title: "",
    thumbnail: "thumbnail_34",
    type: "CONTENTS",
    url: "https://youtu.be/008C6BvS3E0",
  },
  {
    idx: 36,
    title: "",
    thumbnail: "thumbnail_35",
    type: "CONTENTS",
    url: "https://youtu.be/hF4kw7AeeF0",
  },
];

export default videoData;
