const videoData = [
  {
    idx: 1,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/EMSqSg2YEck',
  },
  {
    idx: 2,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/BUKb80YVbjE',
  },
  {
    idx: 3,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/Z5GMakXNlNM',
  },
  {
    idx: 4,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/YonedcN4K6Y',
  },
  {
    idx: 5,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/YCOS8V3OicY',
  },
  {
    idx: 6,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/nhNRYswYj0c',
  },
  {
    idx: 7,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/YfoklQho-88',
  },
  {
    idx: 8,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/4qS6baU_Jjw',
  },
  {
    idx: 9,
    title: '',
    thumbnail: '',
    type: 'CONTENTS',
    url: 'https://youtu.be/CMpMLEzoaI0',
  },
  {
    idx: 10,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/y2Gkgm0NvwA',
  },
  {
    idx: 11,
    title: '',
    thumbnail: '',
    type: 'SHORTS',
    url: 'https://youtu.be/t7yfVyPWV6w',
  },
  {
    idx: 12,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/uxJeskw3D6c',
  },
  {
    idx: 13,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/nkaVI-qfA6Y',
  },
  {
    idx: 14,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/1TnkprdNanY',
  },
  {
    idx: 15,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/ikxuOqNMjP4',
  }, {
    idx: 16,
    title: '',
    thumbnail: '',
    type: 'M/V',
    url: 'https://youtu.be/e3YWwoGRBPw',
  },
  {
    idx: 17,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/JopnzS4zLrU',
  },
  {
    idx: 18,
    title: '',
    thumbnail: '',
    type: 'COMMERCIAL',
    url: 'https://youtu.be/Nk25LLkaXCM',
  },
]

export default videoData;