import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { Inter } from 'next/font/google'

import styles from '@styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Studio Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrap}>
        <Link href="/about">about</Link>
        <Link href="/works">works</Link>
        <Link href="/contact">contact</Link>
      </main>
    </>
  )
}
