import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"

import styles from '@styles/Home.module.css'
import homeLogo from '@images/logo_home.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Studio Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.homeWrap}>
        <div className={styles.homeLogoWrap}>
          <Image src={homeLogo} alt="home logo"/>
        </div>
      </main>
    </>
  )
}
